---
title: "Kennedy O'Brien"
---

![*The Tannery in Portlaw was huge but its output complemented its Dungarvan counterpart.*[^1]](images/portlaw_ad_largest_tannery_in_ireland.png)

[^1]: Image taken from Waterford News, 27 September, 1935

[^2]: Image taken from Waterford News, 27 September, 1935

Kennedy O’Brien was one of the few *bona fide* leather men left in early Free State Ireland by which time the tanning industry had dwindled almost entirely out of existence. Yet over the next few decades he helped to build up the industry more than any other person on the ground and his story is an interesting contrast to his colleague-to-be, Austie Casey, because O'Brien was focussed single-mindedly on leather and nothing else, plus he also lived longer to see out his ambitions.

Kennedy O'Brien grew up in Limerick, the son of pig buyer also called Kennedy O’Brien. *Kennedy* was a given name that went back for generations in that branch of the family and census records of 1911 show eleven men in Ireland of that name, possibly all them related as most of them were in the Limerick area, and only one lived improbably far away. There might have been even more *Kennedy O'Briens*, only the Catholic Church didn’t like children to be baptised with anything other than a saint’s name, although family lore claims that there was a cheeky way of twisting the church's arm. Our Kennedy's father simply told the Parish Priest that if he didn't let his son be baptised with the preferred name, then the child would be brought round the corner and baptised a Protestant. This did the trick and thus the curious, heavy-duty, forename lived on.

Our Kennedy O'Brien was aged 22 at the 1911 census, making him a full decade older than Austie. He was listed as an accountant but may have already begun working in O'Callaghan's Tannery in Limerick City, the last surviving large-scale tannery on the island. He was head-hunted by the Managing Director, Michael O'Callaghan, who would serve as Mayor of Limerick before being murdered in 1921, likely by the Black and Tans or the RIC Auxiliaries.[^3] But O'Callaghan said he needed someone to help him estimate the number of hides needed in the factory – clearly a job suited to a man of numbers – but O'Brien already had a job lined up in Dublin and was due to begin a few months later. O'Callaghan said that the clever young man was free to leave when his other job was ready to start. O'Brien took the job and clearly found his place in the world as he spent the rest of his life selling and making leather, as well as spawning a handful of sons who followed him into the trade.

[^3]: <https://www.dib.ie/biography/ocallaghan-michael-a6546>

Having established himself within the Limerick tannery buildings, and built the trust of his boss, O'Brien was given a car and sent out to sell O'Callaghan's leather to the shoemakers and shoe repair shops of Ireland – all thirty-two counties, as partition was yet to be implemented. This constant movement suited his restless nature and it also gave him a great appreciation of the needs of the Irish people, their need for more employment, and the country's need for a native tanning industry, rather than importing almost all of its leather from Britain, much of it made from the hides of exported Irish livestock.

In 1927, O'Brien set up his own business as a wholesale leather merchant, on 27 North Frederick St in Dublin City, and that building would become the centre of operations for his ever-expanding leather empire. It must have been around this time that he became friendly with Sean Lemass[^4] who became known for cavorting with city businessmen, playing golf by day or poker at night. Yet cronyism aside, there is unlikely to have been anyone better suited than O'Brien to the task of planning a native tanning industry, between his years of experience, his knowledge of the entire country from his time on the road, and his deep zeal for employment creation. Thus having the Dublin man's ear would prove most invaluable once the Fianna Fail government took control of the country in 1932 and set out their twin policies of protectionism and decentralization, leading to the establishment of so many factories around the towns of Ireland, big and small. By the mid 1930s, O'Brien's Dublin business was firmly established, so he would have the time and energy to throw into the Portlaw venture.

[^4]: It is not clear exactly when Kennedy O'Brien became friendly with Sean Lemass, and it is not clear if perhaps O'Brien was involved at all in the Republican movement. His father seems to have been sympathetic and his brother is known to have been actively involved as a gun runner during the revolutionary years. Their father, Kennedy Sr, bought and sold pigs in Limerick, and it became Bart's job to walk around with a cart and amass pig swill from the local hotels. This noxious task proved to be the ideal cover for transporting guns because they could be wrapped and placed beneath the swill. And if he was stopped by the police of the auxiliaries, none of them would swirl their hand through the filthy pit of used food. And while this method of transportation befuddled the authorities for a time, word must have leaked out because Bart was tipped off that they were on his case, so he fled to New York where he got a job with the Pinkerton Detective agency and, thanks to his free transport pass, he resumed his gun-running acitivities, only at the other end of the chain.

**Why Portlaw?**

The choice of a settlement as small as Portlaw might seem odd for such a large operation, but DJ Dwyer, in his 1962 study of the Irish Tanning industry, considers it something of a prototypical choice for a tannery. One requirement was easy access to a port (Waterford) as tanning agents had to be imported from around the globe. Secondly, tanneries are better suited to a rural location as the smell and waste are so obnoxious. And finally, there needs to be a lot of water available, coming in and going out of the factory. Water is brought in for the tanning itself and, however unsatisfactory it might be to modern sensibilities, a body of water was needed to dump the untreated waste. Dickens Leather in Dungarvan, located where the Colligan River meets the sea, could take water from the river and dump it into the sea afterwards. The tannery in Gorey had to have a huge waste pipe built, running several miles to the sea, suggesting that politics played a greater role than geography in choosing the town. The Portlaw tannery sat on a bend on the River Clodiagh, a tributary of the River Suir, again providing water on both sides. The site had previously been used for a cotton mill in the nineteenth century, run by a Quaker family. Indeed the town was purpose-built for its workers and, when the tannery finally opened, a former employee of the mill, aged 94, showed up and demanded to be given a job in his old haunt.

It turns out that Lemass was, in the end, somewhat regretful at having chosen Portlaw as the site of the first Irish tannery. The town, or perhaps village, was so small that the meal for the opening ceremony in 1935 had to be cooked in Waterford and transported to Portlaw. Fianna Fail might have gained more political traction by putting it into a town with a much larger population – such as Dungarvan – where the staff's wages could be recirculated more easily, bringing bonhomie to a wider array of voters. Lemass's choice of Portlaw was informed by government officials who underestimated the coming demand for leather as the state sought self-sufficiency. It quickly became clear that their estimate of 225,000 hides *per annum* was too low and so was a second estimate of 300,000 hides, made by Vincent Crowley, a Dublin-based solicitor who became Chairman of Irish Tanners and also the accountant for Dickens Leather.

**Personnel**

While the workers in Irish Tanners, Portlaw were local, the management group most certainly weren't. Kennedy O'Brien became a director and general manager, running the day-to-day operations while his Dublin business ticked over. Crowley was chairman and the secretary was his employee, Dr Jeremiah Dempsey, another city-based professional with his finger in the provincial pie. Despite the name of the tannery, it was actually British-owned and Mary Daly notes this it was registered to the tariff-jumping "British entrepreneur who already owned Western Tanning of Bristol and Redvales Ltd. of Bury." Presumably, this was HG Barlow, the Managing Director of Irish Tanners, Portlaw's equivalent of Reginald Dickens who himself was also present at the opening ceremony, along with Dr Austie Casey and many other prominent men of County Waterford.

In retrospect, it makes sense to view Portlaw and Dungarvan as complementary businesses, run by an overlapping group of people, especially in the beginning. They were not in direct competition because Portlaw focussed on hard leather soles for shoes, taken from tougher cowhides, whereas Dungarvan would focus on soft leathers taken from sheepskins. We might also think of the Portlaw and Dungarvan tanneries as a three-way compromise between three societal forces. The provincial townspeople did the actual work, capital and industry expertise came from British entrepreneurs (but not the British state), while those based in Dublin functioned as intermediaries between the two.

However, a new law (The Control of Manufacturers Acts 1932-4) introduced by Fianna Fail required that the new industries not have majority control from a foreign company. Irish Tanners was in part funded by the Irish Credit Company, represented at the opening ceremony by its chairman, J.P. Colbert.[^5] The ICC was formed in 1933 in an effort to fund the new industries popping up around the country, and it is not much of a jump to imagine that the Dungarvan Tannery, with its complementary output, may have been envisioned as being a second branch of Irish Tanners. However, the ICC did not fund Dungarvan – perhaps it ran out of cash – so Irish capital had to be found from somewhere. We shall see in the next chapter that Reginald Dickens owned exactly half of the shares in Dickens Leather, and no capital came from the state. Thus the Irish interest had to be filled by someone, and Austie Casey and Joe Moloney stepped up to the

[^5]: Colbert, John Patrick \| Dictionary of Irish Biography

| Address | Name | Portlaw | Dickens Leather |
|------------------|------------------|------------------|------------------|
| Dublin | Kennedy O'Brien | Director & General Manager | Chairman & Director |
| England | HG Barlow | Managing Director | \- |
| Northampton | Reginald Dickens | (present at opening) | Managing Director |
| Dublin | Vincent Crowley | Chairman | Accountant |
| Waterford | R J Hearne | Director | \- |
| Dublin | Irish Credit Corporation | capital investors | \- |
| Dungarvan | Austie Casey | \- | Director |
| Dungarvan | Joe Molony | \- | Director |

Managing Portlaw remained O'Brien's primary focus, and by 1957 it was said to be the sixth largest tannery in the world, and managed by his son Bartholemew. His sons became ever more involved in the family business, and Kennedy's urge to create employment and wealth for his family, saw him set up something of a corridor of his own tanneries stretching between Dublin and Waterford. The first of these was in Gorey (1936) and later in Milford, Co Carlow, Rathangan, Co Kildare and Carnew, Co Wicklow**.** Meanwhile, his operations in Dublin continued to grow. He had a team of ladies on one floor cutting upper leathers for the shoe repairmen of Dublin and another team producing metal parts for working boots, parts which previously had to be imported from England.

One final story should illustrate the continued importance of Kennedy O'Brien to the Irish leather industry, and its ultimate demise in the latter part of the twentieth century. Among his many ventures, O'Brien, along with his namesake son, began producing football boots and running shoes, under the brand name *Kayobee*, taken from their initials. Kayobee shoes were worn in 1956 by Ronny Delany when he won an Olympic Gold medal in the 1500m, Ireland's first gold medal since 1932, and the first to be televised. The 1950s would turn out to be the high point of the Irish leather industry, before plastics began to be used, and protectionist policies were relaxed, by Lemass himself. Meanwhile, Kayobee shoes, like all regional brands, would be ousted by some of the most iconic brands in the world, and the Irish tanneries slowly faded into oblivion. Our Kennedy O'Brien died in 1959 and his business was liquidated in 1972. The Portlaw tannery, having let go of its staff over several phases, finally closed in 1985 and the derelict factory was finally sold in 2024.
