---
title: "Kennedy O'Brien memories"
---

Kennedy was one of the very few bona fide leather men left in the Free State because O'Callaghans did the most of the tanning in the country, but it was him that did more than anyone to get tanning back up and running and we'd've never got The Factory here if it wasn't for him.

He's a Limerick man born and bred and grew up playing nothing but rugby, rugby, rugby. And the young fellas are the same because there went to Blackrock College outsid Dublin. That's all he ever blasted talks about when he isn't explaining his silly name. You see his father was Kennedy O'Brien too and there's a heap of Kennedy's out there, for good or ill. and the son is a Kennedy too. Our Kennedy told us a good one about the name. He said the priest wasn't going to baptise him such a name, as it wasn't a saints' name of course, so the only way to twist his arm was to threaten to bring the babby round the corner to the Protestant Church. So that did the trick and Kennedy O'Brien the seventeenth of the name came into the world.

Anyway, so he was back home in Limerick one summer but he had his first job lined up in Dublin, when Michael O'Callaghan – the Mayor the Tans shot, God rest him – came looking for Ken to work in the tannery. They needed a fella good with numbers to work out how to estimate the number of hides in the factory, amongst other tasks, so he told Ken he could take on the work then head off to his big new job once the time came. So of course Ken took the work and never looked back. Before you could say Jack Robinson, he had worked his way out of the tannery and selling leather to every shoe repair shop in the land. All thirty-two counties of course because this was before the country was divided. And he knows every last accent but he says the brother could do them too, because he was also on the road and just had an ear for them

DETAILS OF I\@BRIEN SETTING UP SHOP WOULD BE USEFUL

PORTLAW BETTER OF COURSE
