**Dublin Businessmen**

-   Lemass, Crowley, Cox, KOB, [Notes](https://www.notion.so/2025-12-22-Monday-2d14cfb361648003aa41ed4011ff4128#2d24cfb3616480b796f4df14f329d11a)

    -   friendly with Sean Lemass
    -   disgrace of having leather going out of the country and none of it being tanned

-   KOB and estimates

    -   accountant, numbers man etc

-   Why Portlaw?

    -   surely KOB needed somewhere but not there

    -   cotton factory etc <https://www.portlawheritage.ie/industrial-past/>

        -   *an old man of 94 applied for work in the tannery, said he had been a Malcomson employee, and asserted his name should be first on the pay-roll. Every Saturday he stands outside the paymaster’s office, as if unwilling to believe he has not been included in the latest development*…

-   Dungarvan as a complementary bolt-on

    -   need to c

------------------------------------------------------------------------

<https://www.irishlifeandlore.com/product/tom-obrien-aged-80-part-1/>

-   11 KOB's in the 1911 Census, including his father (a pig buyer) and himself, listed as an accountant.

Kennedy O’Brien was one of the few bona fide leather men in the country

-   survivor of the tanning trade

    -   <https://www.failteromhat.com/kelly1915.htm>

-   Closest thing to an Industry Baron

    -   Family man - each of them got a bit of the business too

        -   A real family business
        -   all of the brothers were involved.
        -   sisters not involved - got married young - didn’t have to have careers

    -   KOB’s story is instructively different from Austie’s because he was a real leather man whereas Austie was a community man and it didn’t matter what the factory did

    -   Austie would have learnt a lot from him

<!-- -->

-   He grew up in Limerick, the son of pig buyer also called Kennedy O’Brien.

    -   It was a name that goes back for generations and census records of 1911 show eleven men of that name in the country, most of them in the Limerick area, and none born too far away. There might have been more men of the same name only the Catholic Church didn’t like children to be baptised anything other than a saint’s name, but family lore claims that Kennedy Senior - or possibly Kennedy Senior Senior, or possibly any of the men looking to have their child named Kennedy - threatened the priest that if the Catholic Church wouldn’t baptise the child with the selected name, then they would go round the corner and have the latest Kennedy baptised into the Church of Ireland.

-   Our Kennedy seems was aged 22 at the 1911 Census and was listed as an accountant.

    -   As a young man, he had passed some exams and was all set to move to Dublin in a few months’ time to pursue a workaday job in his chosen field. However, Young Kennedy was approached by the owner of O’Callaghan’s Tannery in Limerick, a man who doubled up as mayor of Limerick. *This tannery was the last vestige of a once-thriving leather industry in Ireland which had been in decline ever since livestock began being exported safely to Britain in the 1820s.*
        -   Mr O’Callaghan told Kennedy that he had some immediate work for the lad and that he could head off to Dublin when the time came. The lad must have had a good head for numbers, and a reputation for it too, as he was tasked with calculating the number of hides O’Callaghan would be needing for various tasks. Kennedy O’Brien would stay with O’Callaghan for many years to come and he worked his way up the company.

-   In time he became a Travelling Salesman for O’Callaghan, a job then known as a ‘traveller’ and his role was to sell the tannery’s leather to the shoemakers and shoe repair shops around the entire island of Ireland as partition was yet to be implemented. This gave O’Brien a great appreciation of the needs of the people and how badly employment was needed around the country.

-   it's not clear exactly how KOB got to know Lemass, but he may well have been friendly with him before his leather business was set up

    -   Grandfather KOB was involved in the IRB,
    -   whole lot of stables at the back of Fairgreen
    -   used to send around Michael Traynor with a donkey and cart
    -   And all the swill from the hotels would be picked up
    -   and they used to feed the
    -   Turns out that Bart was getting guns and moving them around the city of Limerick putting them into the swill
    -   and if they were held up with by the Auxiliaries or the police there was none of them going to put their hands down into the pig swill
    -   once they figured it out, Bart was tipped off and he ended up in New York
    -   Got a job with the Pinkerton detective agency and in that job he could travel all over the United States \[for\] free. He was running guns to the IRA through the IRB
    -   So he was very involved. He was a complete headcase. Died in 1919 and buried in Grand Conboy in New York. He was the first Bartholemew
    -   It’s not a double-barrel name
    -   sympathetic and supported the movement— he was in danger
    -   he was involved in incidents. he was very friendly with Sean Lemass.
    -   Brother Bart (Tom’s Uncle) was involved with the

    For a time he lived in Belfast where he moved with his wife / met her?

-   He eventually centered his life in Dublin and set up his own business as, primarily, a wholesale leather merchant, on North Frederick St,

    -   In 1927 Kennedy O’Brien set up his own business on 27 North Frederick St,
        -   and this would be the pivot around which his restless life would be based.
        -   His son Tom cannot even count the number of houses they lived in around Dublin
            -   Jones's Rd
            -   Shrewsbury Rd x 2
            -   several others
        -   KOB spent one day per week in N Fred, rest of the week travelling between his businesses
        -   all the time adding bits to the business.
            -   Brands were often built around his name
                -   Neirbo
                -   Kayobee (football boots and runners - soles for shoes used by Ronnie Delany, long before anyone had a contract with Nike)
                -   My father also called Kennedy O'Brien continued in the leather business diversiving into manufacturing sports shoes and made the running spikes that Ronnie Delaney wore for his 1956 Olympic Medal in Melbourne.
                    -   upstairs girls making uppers -
                        -   Upper factory upstairs too
                        -   16 girls working on machines, making uppers for shoes
                        -   selling uppers to the repairmen, custom made by the staff
                        -   customers thought the shoe repairman had done
                        -   very skilled workers - all gone now
                        -   if you had a tear in your shoe they’d stitch it for you.
        -   Character
            -   much-admired by the town,
                -   “nobody works for us, they work with us. We don’t own anybody”
            -   Great respect for the people who worked for him
            -   they’d do anything for him
            -   asked people where the offices and told them he was the grandson of KOB. The whole town were down to tell
            -   Straight-talking, black and white, more of a person person
        -   

-   Businesses

    -   

        -   Irish Tanners, Portlaw

            -   

                <https://www.portlawheritage.ie/the-portlaw-tannery/?utm_source=chatgpt.com>

                Protectionism

                -   led to the establishment of the Portlaw Tannery by Irish Tanners Ltd on the old cotton mill site in the early 1930s, led by managing director and principal shareholder Kennedy O’Brien. The tannery was officially opened by the Minister for Industry and Commerce, Seán Lemass, in 1935.
                -   see Daly & Decision to go to POrtlaw based on underestimation of the needs
                    -   KOB as managing director and largest shareholder?
                        -   but which british company owned it?
                        -   set up in 1935 in collaboration with a British entrepreneur who owned Western Tanning of Bristol and Redvales Ltd. of Bury.
                -   Jeremiah Dempsey, an employee of Kennedy, Crowley and Co appointed the first secretary and accountant (1935–6) of Irish Tanners, Portlaw. <https://www.dib.ie/biography/dempsey-jeremiah-francis-a2520>

        -   Milford Tannery (1948)

        -   Dickens Leather director

            -   1935 - Austie & Dickens present

                -   The doctor adn I were much fortified from the technical end of the industry by the presence of Mr KOB, a well-known fiture in the Leather Trade, a Director of the Portlaw Tanner, and subsequently the first Chairman of our own Board of Directors" w

                <!-- -->

                -   Max Davis bought 500 of Kennedy O’Brien’s shares soon after the sales. Dunno why
                -   This was before the ledger book was created.
                -   Kennedy O’Brien was responsible for 1000 shares, but only kept 997 of them, leaving 3 shares for his audit clerks, #10001, #10002, #10003

        -   Irish Textile Leathers (rathangan?)

        -   The Carnew Tanning company - director - Tom involved in that

        -   Tannery in Portlaw

        -   Managing Director in Dickens Leather (check how long)

        -   Shares for sale?

            -   check the names and addresses of clerks (Crowley I think)

<https://nationaltreasures.ie/submissions/W2O4BJ?utm_source=chatgpt.com>

national treasures

Kennedy O’Brien - grandchild - **Geraldine O'Brien**

Portlaw

-   Portlaw heritage aug 2025

    -   <https://www.waterford-news.ie/news/heritage-week-was-great-success-in-waterford-as-historic-business-recalled_arid-70014.html>

        Kennedy O’Brien, first Managing Director of Irish Tanners,

-   Huge Painting of Kennedy O’Brien

    -   accounts for Irish Leathers
    -   Portlaw
    -   samples of leathers
    -   Ken O’Brien
    -   article he delivered
    -   slides and names mentioned
    -   handwritten notes

-   Photos

    -   <https://catalogue.nli.ie/Record/vtls000595086>

-   

    -   Irish Tanners
    -   250
    -   It was hoped that 'the Free State market for leather and the protection afforded by the tariffs are sufficient to ensure good dividends on the company's capital'.35
        -   This tannery was said to be the sixth largest in the world in 1957. Who owns whom records it as owned by UK firm Allied Leather. It employed 250.

"This sample swatch of leathers connects me to the model town of Portlaw in Co Waterford.The factory & town was set up by the Malcolmson family to employ & house their cotton workers circa 1840, the factory was a steel framed structure said to be the largest single span building in the world at that time and turned over 2M of raw cotton and processed 6M yds of calico. After the American war of independance when protectionist tactics were introduced the Irish cotton industry declined and the factory and mill closed. Subsequently the Portlaw Spinning Co. took over the mill but the company had a short life span survive closing in 1904. **My families involvement with Portlaw started when my grandfather Kennedy O'Brien set up Irish Leathers in 1920 taking over the factory buildings in Portlaw in 1932 and employing several hundred employees at the height of the tanning industry until the introdution of plastics into shoe making which heralded the downfall of the leather industry in Ireland and the company closed in 1980.**

-   My father also called Kennedy O'Brien continued in the leather business diversiving into manufacturing sports shoes and made the running spikes that Ronnie Delaney wore for his 1956 Olympic Medal in Melbourne.

-   I found it facinating as a child to visit Portlaw and the other tanneries my grandfather and his children had an involvement in and

-   spent many hours in the **North Fredrick St. factory in Dublin** seeing the cutting and forming of leather into shoes instilling in me a 'can do' attitude and encouraging my interest in business, and of course my love of interesting leather shoes.

-   This piece of leather from the Irish Tanneries swatch housed in the Portlaw Heritage Centre and who kindly gave me a piece when I visited last Nov 2016, reminds me that my life is made up of lots of happy childhood family memories around leather."

Submitted by: **Geraldine O'Brien**

### Kennedy O'Brien

-   

**CAtherine Casey's funeral**

-   Kennedy O’Brien sent a telegram from Dublin

**Shares**

**Kennedy O'Brien** (founder Irish tanners Portlaw),

**Portlaw Tannery**

-   e largest tannery in Ireland
-   concrete building 1945

<https://portlawwalkingtrails.wordpress.com/2017/12/16/irish-tanners-portlaw-in-the-20th-century/?utm_source=chatgpt.com>

Limerick Tannery

<https://limerickslife.com/ocallaghan/?utm_source=chatgpt.com>

Further info:

-   Ger Crotty call

-   Family members

<!-- -->

-   KOB

-   Arthur Cox

-   Vincent Crowley

I bought and downloaded this mp3 file for E10

I met Tom O’Brien at his own home, where we spoke about the day his father started work in a tanning factory in Limerick city, run by the O’Callaghans. He described his father’s early days growing up in the city, and his involvement with the Garryowen Rugby Club in the early 1900s. The family moved to Dublin in 1927, where his father set up business as a wholesale leather merchant under the title of Kennedy O’Brien and Company Ltd (Kennedy was his father’s Christian name, a name which can be traced back in the O’Brien clan). Tom himself began work in his father’s tannery in Milford in 1948.

Opening Dungarvan Observer

[https://archive.waterfordcouncil.ie/Historical Newspapers, Books and Journals/Newspapers/Dungarvan Observer/1937/Dungarvan_Observer_05_May_08.pdf](https://archive.waterfordcouncil.ie/Historical%20Newspapers,%20Books%20and%20Journals/Newspapers/Dungarvan%20Observer/1937/Dungarvan_Observer_05_May_08.pdf)
