---
title: "Chapter Plan"
---

Here's a plan of chapters.

A few secton have already been written and will give an idea of the mood so far (in bold below).

They can be found here

<https://a2dez.github.io/casey_blog/posts/kennedy_o_brien/>

**Family background & early years**

-   Michael J & Catherine Casey, five brothers + one sister, Grawn sold, Clerical history in family. Land league etc.

-   Departure for Dungarvan. Family business. Death of Michael J. 1923, Catherine & Pierce run the shop.

-   Austie early years in UCD and then as a Dispensary doctor in Cappoquin and Dungarvan

**New York**

-   Richard J: revolutionary background in Maynooth seminar

-   off to NYC, grows his congregations, gives speeches over several years

-   rousing crowds, raising funds, and contributing to the Dail Loan (possibly involvement of Joe Casey)

**Establishing Dickens Leather**

-   **Opening Ceremony, 1938**

    -   all of the below characters introduced

<!-- -->

-   Fianna Fail, Protectionism & the power vacuum, policy of self-sufficiency & decentralization

-   Brits in

    -   the need for capital and know-how in a state that can't support itself

-   **The history of the Irish leather industry**

-   **Kennedy O'Brien & Portlaw Tannery: a one man leather empire**

-   **Reginald Dickens**

-   Dublin Mediators

    -   Arthur Cox (lawyer), Vincent Crowley (accountant) and the Knights of Columbanus

-   The Dungarvan Scramble for a factory (any factory)

    -   FR TB Walsh, Austie Casey, Joe Moloney

    -   Fianna Fail Cumann & Dungarvan Industrial Development Council

-   Raising Money

    -   Austie gathering contributions

    -   Richard J's background in crowdfunding and raising a congregation.

    -   Jiggerpokery –\> Richard J buying shares off Austie, Kennedy O'Brin & Max Davis, etc.

**Richard J Casey 1924-49**

-   Army Chaplain

-   gradually buying more Dickens shares –\> making money from sweepstakes (need more evidence).

**Up and running**

-   Dickens leather 1937-1951, day-to-day

-   Glue and Gelatine factory & life in The Emergency

-   Exports

    -   Trips to America, Canada etc, late 1940s, Austie, early 1950s, Pierce

-   Death (x 2) & family fallout. Richard J as executor.

-   
