---
title: "History of Leather in Ireland"
---

**History of tanneries**

As I said, we had no clue about how to make leather, because there was barely a tannery left in the country, bar the one that Kennedy worked in for years, O'Callaghans in Limerick. Kennedy was steeped in leather. He knew the history of it, and he had been to the four corners of the country selling leather so he knew everyone and everything there was to know. A hundred years ago, he said, every town and village in the country had its own little tannery, no matter how small. He told me that before the famine, there was nearly 50 tanneries in Cork City alone, tanning a couple of thousand hides a week, and between the lot of them they had more jobs than we have today in all the tanneries of Ireland. And he said it wasn't just the famine that did for the industry. It was shipping that started it. You see, once the ships could pass safely and reliably from Ireland to England, with lighthouses and so forth, and that was before the famine. So the Brits could just start dragging all our livestock out of the country. Cows. Sheep. Pigs. Feckin Goats. The lot. And with the livestock went the jobs. It was in Britain that the beasts were butchered and in Britain that the hides and skins were tanned. And a lot of it done by Irish fellas who had to emigrate there for the work, when we could have been doing it here ourselves, and keeping our communities alive. The whole fiasco made no sense.

And there was more. We didn't have any dyes from the oak trees because all our forests had all been chopped down, and anyway, our leather wasn't half as good as theirs because of how they taxed it. The Brits taxed themselves on every hide used but here they taxed the pits, which meant **too many hides were getting shoved through the same chemicals**. Now fellas on farms didn't care a damn about a few blotches on their boots but the highfalutin ladies in Dublin did so they wanted **the finest Northampton leather**. More imports. More jobs in Britain. More emigration. It was a vicious circle.

**Post-treaty Tanneries**

After the Treaty, the department fellas did an investigation into it and they said there was just five tanneries left and the following year, nineteen hundred and twenty-four, the little scutty one there in New Ross closed down. Ireland was only tanning one in twenty of the hides it needed for the leather people were wearing on the feet and all the rest of it. But they never brought in any tariffs for tanning, despite the push for it, only in footwear. I think it was 15% they slapped on shoes and boots, but it **wasn't worth a dram** because the Brits could soak that up. They were already producing huge volumes and the new Irish companies couldn't compete. Then they started coming in here. Eddie Donaghy took his whole factory, lock stock and barrel, over the border to Dundalk, and then a fella called Halliday from across the water set up nearby. Another couple of them went to Drogheda. Before you knew it **half the shoes in the country** were being made in County Louth, and we ended up with a battle on our hands to get the tanneries down our way.

-   At this stage, Irish Tanners decided they wanted to get in on the game, so they put in a case with the Tariff commission but came back with nothing.

<!-- -->

-   ALL that changed after the Depression **(what did they call it?),** because all of a sudden The Brits were running out of business, at home and abroad, and

-   This of course changed with the arrival the Fianna Fail government in 1932

-   

So we had to shout loud to make sure they didn't put all the tanneries up there near the shoes.

-    Worthington was in Drogheda

But it was ten years before anything of use happened in tanning, when Dev got in and Lemass started sorting out his department, but there was a bit of progress in footwear beforehand they explained.

**Location**

So they sent a couple of fellas over to

. **FOOTWEAR LEVIES ETC**

Of course the tanneries kept on closing even after the Treaty. The department fellas said they did a report soon after the Civil War

The scutty little one in New Ross closed down in '24, and only a couple more little ones survived by the time

them and the Brits that had the hides for making leathe.
