---
title: "The busiest man in town" 
---

**Opening scene, potentially**

*Austie is in bed and Laura Anne (aged 2) has come in and is bouncing on the bed. Austie is in awful **Yet to be identified** pain so he calls Michael (8) to come and help him get rid of Lala. Not sure where Jane and Richard are – if anywhere. Ann is in bed pregnant and not well*

**Notes - Austie could die before he tells the full story**

**What curse of pain would he use? (e.g. Lord of Mercy)**

Next - breakfast in bed and someone will come in to start talking to Austie to hear his story

-- Bounce, bounce, bounce! Daddy, look at me! I bouncing. I bouncing.

-- Ah, Lala, leave me alone, you little rascal. **Lordamercy**, the pain. -- Michaeeeel!

*Oof.*

-- Morning, Daddy.

-- Morning, laddie. You're very good to come. Would you ever take your little sister or tell **your nanny** to take her.

-- Yes, Daddy.

-- How's your Mammy this morning?

-- She's the same, Daddy. **add pain detail**?

He waddles a few steps, his hands around a big imaginary belly.

She misses you.

**Austie will be sentimental here. He'll want to hear something nice about Michael. About something little Michael loves - something that will help Austie die in peace, knowing he has raised a good little boy.** *Jesus I'm in tears now . I'm thinking Michael would be a books man. He becomes a James Joyce scholar later in life.*

-- Michael did I ever tell you how I fell in love with your mother

-- No daddy. Did you not always know her?

-- No, no. He chuckles. I'd never met anyone like her. You know youre mammy. So loving. So welcoming. And she was so beautiful. ***gerrup ya good thing ya!nAME a film star from the era.** And she was to be mine. At ong last. The quest was finally over. All that galavanting finished and I could relax at last.*

**Need details about Ann.**

**copilot ann to get a film star like her**

-   bunnie had a farm with a thatched cottage

    -   didnt she put up de valera when he was on the run

    -   bunnie's residence was very near carrigle near knockaun

    -   anyway we'd be out there doing the ?fields (creamery?)

    -   your mammy was in Kiereen dispensary and oh I fell in love with her that day. of course i had known her for years. she was Tim Foley's eldest. *and a lot younger than me, **rahoo**. and I had my eye on her a long time before but i stayed away from her til then because she was too young. Not ready yet. But a fella told me how you know if they're old enough and my time had come. Oh she was a beauty. I was forty two. You divide that by two.*

    -   Michael what's forty-two divided by two?

    -   Twenty. Two, daddy. Twenty-two?

    -   nearly. twenty-one. and add seven.

    -   twenty-two plus seven is twenty-nine daddy

    -   well she was twenty-eight now. nearly. A big girl at last. And I was getting far too old. Jesus, Michael I had ye all too old. God love you. I haven't the same energy I had. Jesus I never stopped. And now ye'll all have no...

    -   

J/ The mother didn’t get the clinical job in Dublin. So she ended up doing a locum in Keereen. We had a coousin who featureed very big in our lives, bunnie sullivan. but bunnie hadd a farm with a thatched cottage

L/ Knockaun

J/ Didn’t she put up de Valera, when he was on the run

L/ Bunnie’s residence was very near Carriggle near knockaun

J/ anyway we’d be out there doing the ?fields

**mammy was in kiereen dispensary and my father loved women he had pretty womein he was cruising with the women**

**anyway bunny had an orchard and mammy,**

**our parents courted in the orchard** (in Bunny Sullivans)

**L/ but where did she meet austie casey?**

**J/ he found here cos sshe did the locum in Keereen and he was the dispensary doctor in dungarvan**

**L/ would keereen not have been part of the dungarvan practice at the time**

**J/ he decided he wanted to fall in love with her**

## **Austie meeting Ann**

-- So it wasn't love at first sight, then?

-- Ah no, I wouldn't put it that way. Sure she was only a young one, a thin pale soft shy slip of a thing, and she was Tim Foley's daughter, and like another mother to his children. She was caught between two stools. She had no job yet and she was stuck in the nest looking after that long string of chicks in her wake, half of them with a mouth full of Latin and no shoes on their feet.

-   There's not many of her kind around these parts, so you have to be cute.

-   I was playing the waiting game, you see, because there's not many of her kind doing the rounds.

I would see her around here and there, but we never went courting. I remember her well at the opening of the factory, the official one, but she was only nineteen or twenty, and me a big sturdy fatso ripe for early retirement, my hurling days behind me, with a whiskey in one hand and a cigar in the other, ~~blabbing along to the big shot Jackeens~~ ~~like Lemass and fat Ken~~.

Now we crossed paths here and there over the next few years but the stars were yet to align. I had my head down. I had my practice and we had the factory and I didn't want to give those up, but sure you can't stay away from the best ladies forever. Ann was finally breaking free of the coop. She was out doing her father's locums because he was all the time sick then, God rest his soul, and she was finally free. She'd go out on her bicycle and her gorgeous dark hair sailing in the wind as she flew down the hill. *And a lovely little rump on her as she went back up it, her hams moving as she stood on the pedals.*

So anyhow it must've been '42 or '43 - during **the War** of course – and I met her there in Bunny Sullivan's. **check catchment areas - maybe Ann was visiting Bunny and Austie there as a doctor?** And it was a gorgeous day and we just had some time to ourselves. Bunny wasn't well so I drove over and Ann had cycled over as a visitor. She wasn't there in her capacity as a doctor. Bunny had a dose and was in bed so Ann said she'd pick a few apples and bake her a tart then she asked me to come out and help her. Of course I knew what she was up to. It wasn't like I was going to reach up and pick the apples she couldn't reach. There was something so deliberate about her intentions but in the best of ways. She knew exactly what she wanted and it was only then that I let myself go. She wasn't just a pretty young thing from a different world. She was connected to me now. Her beauty was focused on me, that smile, those eyes, those perfect hands as she plucked the apples and placed them in Bunny's basket, and she says hold this and she puts one foot on a bough and a hand on a branch and reaches out full stretch for two more lovely apples, those long legs taut, and she spins back around to me only she's spun too far and she wobbles and yelps and drops down onto me and I have to drop the basket so as to catch her and her head is over my shoulder and she laughs and smiles and she didn't demur. Kiss me she said. Kiss me now.

And I said haven't we the apples to pick back up, and she laughs and says oh you're a good one, Austie Casey, this won't be the last you see of me, and sure he was are now.

her eyes demur and she pulls her head away from me but there's not going back now.

**WHAT WOULD THEY SPEAK ABOUT**

-- and how is it that a fine man like you never met a nice lady?

-- hows business?

--

-   she invited me out

so Ann and I went for a walk out to the orchard to pick a few apples. Good old-fashioned courting

It was years later - '42, '43 or so, and we were out in Bunnie Sullivan's. She was there doing her father's locums and she was plenty ripe by now, must have been twenty-six or seven by then *That perfect age where they've calmed down but the body hasn't gone rotten yet.*

**Ann & austie courtig in the orchard**

## **Valentine Ryan, hurling**

\- - There was a young fella came down from Dublin and I've never seen a fella with as good an eye for the ball. Valentine Ryan was his name, from a farm up in the North County somewhere. Newtown, Oldtown was address. I remember that cos it was gas. We put him in goals because he was tiny but he could stop anything. **Fr Hurley** couldn't believe it. Hetook him out to the pitch one of the days and smashed twelve shots at him and he stopped every one of them. **Hurley** never said a word after but we all knew. The youngfella said there was no hurling where he came from, only cricket down the road, no less, so he and the brothers made their own hurls. I've never seen a hurl so strong. He got it from the base of an ash tree and nothing would break it. One of the fellas borrowed it one day when we were playing **STRONG HURLING CLUB** and he said it was great. He smashed two fellas' hurleys with it.

-- And where the feck did he get a name like Valentine? Was he the Pope's child?

-- He said he was born the day *after* Valentine's Day. Twenty past midnight on the fifteenth of February and his mother asked the midwife if she could back-date the birth but she was having none of it, the aul wench. But the mother had her heart set on the name. Val said he has an elder brother, Larry, but the full name is Lorenzo, named after Cardinal Lorenzo something who was here for the Eucharistic Congress in '32. **Dickie** would know him. And he'd a younger brother by the name of Columbanus, no less. The mother must have had awful notions, and Valentine only down here to learn about the chemicals in the factory.
