---
title: "Opening Ceremony Perce"
---

People

-   Urban council

-   Gardai

-   Band

Details

-   Lemass's car & entourage

-   Abbeyside attitudes (is it a trek?!)

-   Blueshirts in Dungarvan

Language

-   out of the blocks - should it be GAA

Searching

-   Oral history, phrases etc.

    -   Waterford Oral history

        -   https://media.heanet.ie/page/e8eb12f5b33b4652a62e9fe495bf3a83

------------------------------------------------------------------------

------------------------------------------------------------------------

Of course Austie was first out of the blocks to meet Lemass. We went all the way over there to Abbeyside for some reason and the lot of them showed up in the big car that would put Dickie's to shame. I don't know where he was for the day. Very odd altogether. Normally he can get out of anything. So anyway, Lemass is first out of the car, with his big shamrock-green tie on him, and skinnymalinx Dickens is there beside him with those funny gloves in his hands. That Kennedy O'Brien fella – such a name — stumbled out next with his big belly and his watchchain jiggling. I'm surprised some rascal didn't run and yank it off him at some point. Maybe they were afraid he'd grab them and eat them.

So Austie is there saying hello sir and how are you with his big sour face, and it must have been an awful long journey, but these fellas spend half their life in those cars. O'Brien is up and down to Dublin every week and Lemass is all over the country, with all these factories he's opening the length and breadth of the land.

So it's all handshakes and nods and how's the missus this and is the young lad still at the hurley. Dickens hasn't a clue but Austie has his arm around his little shoulders and he gets himself into a nice position at the front of the march as they go over the bridge, with the whole town lined up on the side of the road. The council are there next (**DETAILS**) and Duffy and Walsh and all their little Garda minions are there with their straight backs.

So the band lead the way ([SONGS](https://www.notion.so/2026-01-19-2ed4cfb3616480c8b18dfae622e71423?source=copy_link#2ed4cfb3616480abbfdcd32df1bcf2f9)?) and we all file in behind like we're queueing up for communion, big smiles on everyone's face, and the kids all messing and running round. The place is nothing but noise and colour with all those silly triangles overhead. I'm a few rows back but mammy gives me a little nudge and I'm not far behind Austie now and I can feel the crowd all looking at us.

Once we get to Quay St, the whole staff are lined up, a hundred fellas with the stench of pickle and dead flesh, the smell hitting us first, the big dirty faces next. The poor sods were barely given an hour's break for the occasion. I don't know how they do it.

When we get to The Lookout, they've put up a platform and your man O'Brien Kennedy, or whichever way round it goes, is up first but he is standing there looking out at all of us while the band break into the Amhrainn. He starts by welcoming Minister Lemass and then leaves it to the town legends. Michael Morrissey and Willy O'Meara say a few words to Lemass, and then it's Fr Walsh's turn. The two Cumainn are up next in support of these Fianna Fail fellas and then Lemass comes up at last with his big tan and pointy nose and Jackeen voice.

\
"I wish to thank all the public bodies who have presented me with addresses of welcome and in a special way, the workers of the factory and the two Cumainns'

"If the establisthment of the factory in Dungarvan will help to restoree the prosperity of this town and to provide new opportunities for employment for its young men, any little assistance that I, in my official capacity, might have been able to give will be more than repaid"

"I wish to congratulate the directors of the enterprise won the success which has attended their efforts so far and I hope the success would be continued into the future"

The band blast out Faith of our Fathers next and then Bishop Kinane has his turn and he blesses the factory.

starts welcoming the same Minister he came down in the car with. \

and then we coming at us before we even greet them

hundred of them a. Down near the lookout, the last few of them have poked their heads out of the factory, the one, all filthy from the
