---
title: "John Egan"
---

John Egan was one of those fellas. He was **twenty-four** when he was shot and had never had a job. But there was a spot lined up for him in the factory.

------------------------------------------------------------------------

**John Egan**

The death of John Egan really shook Austie. He was in the Commercial Club of a Sunday evening, several pints deep, when he and his companions heard a volley of loud bangs nearby, like a car backfiring or something. None of them had heard a noise like it in ten clean years or more, and they had mostly forgotten the horror they had come to know during the Troubles. Until now, when it all came back. Two things happened at once in his mind. As a doctor he immediately slipped into work mode. Alert, agog, afresh, ready to get to business. He knew there was work to be done and he was well used to being interrupted like this. At least he wouldn't have to get into his car in this state. But as a former soldier, something cracked in him. He felt a split in his body and in his mind, like lightning or an electric shock carving him into two separate parts. One part here and one part back there, in the hills, in the action. Men screaming as he tried to look after them. He heard their roars in his head, echoing, echoing, Help me Michael. Help me. I can't, boy. I can't, he thought, as he tried to comfort them. The terror. All that death. It wasn't like all the other kinds of death he had seen since then.

When he got to John Egan round the corner on Mitchel St, he would see that terror again. A crowd had already formed around the dying body and there was no sign of a car now. Fr Hearne was knelt down by his side, anointing the lad and someone ushered Austie through the helpless onlookers, but his efforts were no more use than theirs. Save me, said the lad, save me. I'm shot. There was blood gushing out the back of his head and dribbling out the side of his mouth. The skull was smashed and bloody, brains bursting out. There wasn't a hope. You feckin eejit, boy, Austie thought to himself. What did you say to them? Who did you speak to? It's not worth it now. It's over. The game has changed. We got our freedom and now it's time to cash in. You were too young to be a hero and now you're just a victim. You had a life ahead of you. Didn't we have a job for you lined up in the factory and wouldn't you have been able to put food on your father's table, with your seven hungry siblings and your mammy full of tears now.

"Here's your mammy now, boy. She can do more for you than I can". Mrs Egan had been out looking for her son to warn him. It all happened so fast. It was barely twenty minutes since those fellas drove to her door looking for her John. She never told them where he was but she and her husband went down to the dance in the Town Hall to dig him out and tell him to be careful. John told them to go home and he'd be home after but they shouldn't have left him off on his own. Mrs Kirby said he and a few of his friends came in to her shop for a glass of milk, and after he left, the people in the car called him over and just started shooting. He was hit four times. In the leg, in the chest, in the mouth and in the skull. Jesus, Mary and Joseph, it was brutal. The car zipped off immediately

There was

There was only ossified terror in John Egan's eyes when Austie got to him because he had died immediately. Gunshot wound to the head as he told **garda who** afterwards

------------------------------------------------------------------------

-   fellas went for a glass of mild in Mrs K Kirby's shop

= save me, save me, i'm shot

-   FR Hearne was going to bed and heard a motor car outside

    -   thought he heard the car backfiring

    -    and anointed him

        -   

Dr Casey heard what he thought to be shots

-   he happened to be in the Commercial Club nearby

    -   thought to be the back-firing of a car

    -   oh, my poor boy

    -   Fr Aherne was attneding him, keeling on the fringed of the pool of blood, and the boy was surrounded .

    -   young egan was bleeding profusely, principally from the back of hte head and also from the mouth. He estimated that he livd some ten minutes after being shot

    -   Gardai were on patrol in the car

        -   revolver bullets found subsequently

    -   streets were thronged with citizens discussing the awful tragedy

= The deceased was still bleeding profusely from the left side of the head and neck

he had a wound in his upper lip on the right side. he died about five minutes after the witness arrived

-   

-   austie assisted at the post-mortem on Monday evening

-   four entrance wounds & three exit wounds were found

    -   two in the head, one in the chest and one in the left lef

    -   fourth bullet was found in superfiical skin at the back over the spinal column

-   Supt Walsh - would your examination lead you to think that the shots were fired at close range

-   Dr cASEY REPlied yes, there was some singeing

-   head wounds alone were sufficient to cause death

    -   right lung and organs.

    -   left side of the neck below the lob of the left ear trhough the mouth and upper teeth, with an exit wound to the right side of the angle of the mouth

    -   shatterned the skull over an ear of three y one and a half inches

    -   brain matter torn through the xit wound on the left side of the head

        -   death due to shock and heamorrhage cause by the wounds on head and neck

    -   Car seems to hav ebeen stolen from District judge, mr troy in Fermoy - armed robbery at his house Chrysler car

        -   found abandoned between Cahir and Clonmel, near Moll's Cross

        -   raiders were most courteous and appeared to be rather nice men

-   John Egan bio

    -   24, unmarried, promised a job at the new leather factory

    -   model son and a daily communicant

    -   hurling and football clubs, blue and white bage on mourning armlets

    -   O'Brien PP, TB Walsh, MF Hearne, J

-   <div>

    -   head

    </div>

john_egan_Dungarvan_Observer_05_May_02.pdf

1120 Sunday Evening May 2 1936

-   party of armed men in a motor car

-   outside the presbytery

-   Mitchel St, lived with parents, eight kids, unemployed

    -   Egan at the dance in the Town Hall

    -   Men came to his home at 11pm

    -   parents walked to Town hall

    -   "Go home and i'll be home after you"

**Need to think of something that triggers PTSD. For me it was traffic light sounds. not cos that was the sound of what i remember, but it was a sound that reminded me of jaywalking, a crime, and the crime reminded me of the cops and bitegate. For austie it is obviously something different. It could be a flower! It could be a type of clothing. Need to find out options**
