---
title: "Austie and Lemass"
---

-   You city fellas have no idea what it's like for us in the countryside

-   Sure haven't I visited every town in the country this past three year?

-   Every town maybe, but you haven't seen what it's like for us poor doctors, tramping up the fields in our wellies, with a briefcase in one hand and maybe some rosary beads in the other cos it's a fat lot of good we can do for the most of the patients out in the middle of nowhere.

-   And I suppose the rumuneration is pittance?

-   You took the words right out of my mouth.

    <div>

    Trampling up in wellies

    </div>

-   You're some man to stick out in a crowd, Seanie

-   Yeah well at least I'm not some man to stick out in a photograph

-   Aye, and we've no idea either how youse gombeen men organize the town among yisserselves. With your big thick heads and fingers

-   

-   Lemass had not trouble with confrontation

-   unlike Dev who wanted yes mens

**This could be converted into a conversation between Austie and Lemass in the jacks at the opening ceremony**

I haven't seen Lemass in a long time now, since the factories got under way, but he's a great man, a man of conviction, of ideals, unlike the fellas that came before him. He's always maintained that the problem with the pro-treaty crowd was that they had no convictions. They were men who were happy to settle for second best and while that brought peace it couldn't bring prosperity because planning for prosperity requires prioritization. And if you have no convictions, you can't prioritize one group over another because you are too soft to upset the crowd that loses out. During the thirties, it was us industry men who were the priority and the cattle men lost out. So for the ordinary man, there were jobs in the towns now but not on the fields. Sure there were guards out seizing cattle all over the place and they had nowhere to put the feckin beasts so they ended up being slaughtered. But Lemass could live with that because his convictions told him so. He had seen a lot and he could live with a few dead cows.

But you see he was also a man who could organize other men, and that was why he was good for the country. He knew from the brigades how to pull men together and stop the squabbling between them. He told me a good one about when he first started in the department and he wanted to meet all the staff working for him but they wouldn't meet all him together in the one room. He wanted to know what was going on and they told him how it was. That fella doesn't talk to so and so, and those two won't sit in the one room together. And so on and so forth. So he brought in a fella called Leydon to sort it all this damn nonsense, he called it. Anyone who was not prepared to put their differences aside could move on. Soon enough the whole place was ticking and if Leydon didn't have their cooperation, I'd say they knew all about it because Lemass had no trouble letting men know who was boss. Before you knew it the department had to bring in a heap of extra men – the right men, qualified men – to do all the extra work that came with setting up factories all over the country. He was a good judge of character, Lemass, and he knew how to choose his staff. And he wasn't afraid of a battle, you see, so when his men put it up to him, he could take it. He maintains that Dev was a fierce man for yes men

You see, the department was lashing out grants left, right and centre in the thirties and it was a free for all for us.

-   ruddy faced gombeen man

-   Problem with British companies

    -   there was no enthusiasm at all on the part of the british firms that had been inovlved in the market her to rish themselves here partly because of the policioal set upa and partly cevaause o the world economic slimp which depiremd them of resources for investment.

    -   1930s crash

        -   it is very difcult to envisage nowadys (1960s) a world situation in which factories in Britain were closing down by the hundress

-   competition

    -   we felt that the only was of getting industry off the groudn at that stage was to rely upo n irisih firms by assuring them they wouldnt be in competition…

-   capital costs cheap and low initial outlayss

-   decentralise

    -   there was alsoi this idea of trying to **decentralise** industry

------------------------------------------------------------------------

-   

-   The department got him for us. You see our job was to gather up the money and the department would get you everything you needed. The factory, the machines, the director, the engineers, the managers. **The whole kit and caboodle.** All we had to do was train the young lads in the town **down** in the new **tech**\[nical college\].

    -   

    -   Lemass needed a soft leather factory because Portlaw were doing all the hard leathers and if you're going to be self-sufficient, you need one of everything. No doubling up. We couldn't have set up a hard leather factory because the country already had one.

    -   

    -   But sure we hadn't a clue. None of us in the town knew anything about leather. I remember Lemass telling me we might be getting a soft leather factory and one evening I had to go over to ask Rita in the little library if she had any books on leather and how it's made. Of course there was nothing so she sent me up to Lismore to see Frank Murphy in in the county library. He knew everything about Dublin and his father was a professor in UCD. Frank sent me to the library in ARCS on Merrion St and they dug out a few trade manuals. So Myself and Joe Moloney and Father Tommy were there reading on the morning of the meeting, reading them frantically. Kennedy O'Brien walked over to Bewleys and told us everything we'd need to know about **THROW IN A FEW quick DETAILS**

    -   

    -   Anyway – where was I? – there was no better place in the world for leather than Northampton \[**explain the land\]**. It's the capital of boot and shoe production. The department sent a couple of civil servants over to assess who'd be the best man for the job. **There was no use getting the bigger leather factories. They had enough going on.** They said they loved Dickens's because they had nothing but men working for them. Even the typists in the office were men. There was only about fifty of them and they could see that Reggie was hungry. **.** Give it to the fella that wants the job. The brothers were older than him and he wanted his own show. They were much older and they took over the factory from their father when he had a **coronary**. Like myself. Forty-two or three he was only, I believe. Then the brothers kept it running during the war while Reggie was off fighting. o when he came back he was further down the line of succession.

    -   

    -   

        -   

        -   The lads were all **thick as thieves and played soccer on a Saturday \[rugby in Northampton\].**

        -   

    -   

    -   

        -   

        -   because the land is so good round there. **it's not that different to WHERE IN IRELAND. Cows, sheep,fiels**

        -   

    -   

    -   Dickens was dyed in the wool leather, leather leather. His father was a leather man and his grandfather too and all his brothers bar the youngest one, Frank. **We got to know them well over the years / before the war when we went over to visit Northampton**\[???\]

    -   

    -   But you see Frank is a chemist and a good one at that. I think they made him a fellow of the Royal Society not too long ago, and he has been able to keep us up to date on the latest developments. Reggie gets advice from him, you see.

    -   

    -   

    -   

    -   who was a chemist and sure he was a great help too \[**because he taught Reggie and the other brothers everything they needed to know about the newer chemicals and that's why Reggie was so helpful for so long as Technical Director. Sure Frank is in the Royal ???? of Scientists**

    -   

-   
