---
title: "Woman in the window"
---

**Bitches in the Beaches**

**Beaches Brew**

There she is again now at her window. Like Miss Havisham. The Missus must be gone out with those silly little dogs. Oh Lordy when is she ever going to stop looking at me? It's a good thing she's not in the nip again. Mind you that's the best part of her 😉. The bit that hasn't rotted away like her sorry soul, God love her. And there she is now with her vacant eyes, staring at me, haunting me. Making me relive and pay for my long and flippant youth. I was only playing, silly girl. We were young. How did you not know? Begob, I was a terror for the ladies. A terror to them too it seems. And now she lies there all day in her bed, inconsolable. Praying for my death no doubt. Well she's getting what she wished for. And I'm getting a lot more than I wished for. Those yelps all night echoing across the walls outside. And it's all my fault, is it? Arrant nonsense. So I did wrong by her. Led her on a little. But what fella doesn't take what he's given? The bed doesn't do them any favours. Just lets them brood and brood. I'd rather my fate than hers, mind, burning out while she fades away under the quilts. Living out the days her body insists upon. Thank God I got Anne in the end, after all those false starts. Can you imagine that wan if I did keep her on. She'd've fallen at the next hurdle. A miscarriage. A dead dog. A wet week. She was destined for the blankets. I just got her there faster.

**Be careful what you wish for.**

You've to be very careful so you do, especially once the money started flowing. There was that younger wan at the wedding, all dolled up in her ice-blue two-piece and that *look* on her face. You'd think that of all the days in all the places you could ever go, the last person worth looking at would be the fella getting a ring put on him. But that didn't stop her. And when they say they'd do anything for a man with money, well I've never seen anything it. She went in to see your man for the job and she must've flaunted what she had – which was a lot, now, to be fair to her – and so she goes on back out to the waiting room thinking about whether she had done everything she could to get job. Then the secretary comes back out with the answer. A Missus Hawkshaw I think it was. And go on so, what is it, she asks. Will he have me? *You can have the job if you marry him*. You can have the job if you marry him! Well I've never heard anything like it. And she took the job. And now she's stuck at home with a ring on her finger doing very little medical work bar feeding the babbies.

to see if she's done everything she could to get the job then the secretary comes out with her yes or her no, and your wan is all expectant

I was lucky I didn't get the younger sister either. She was there looking at me

Catherine Foley Getting a job

Now there's some that would do anything

And poor Anne in there. You couldn't call it a miscarriage at this stage. Oh the poor little

I remember when Lala was

that those two lost souls that have ended up in there somehow

I wonder if the fellas working below know what goes on above their head?

-   I never liked those hospitals either

<!-- -->

-   but why did she have children if she was stuck in the bed?

-   If only that other fella could have swept her away an

<!-- -->

-   \
    \
    **One fella** told me that Granny May was fierce worried about me too.

**Woman in the window**

-   woman who had taken to her bed in her 20s after being rejected by the Doctor. Quite likely that was Austie Casey
-   Miss Havesham was minding her?
-   Back when Sarah Mountain View's mother was young (1930s)

<!-- -->

-   The Beaches,
-   rented from The Dower Family
-   nicer house, became derelict and then d
-   Aunt Ann
-   never left the bedroom
-   May looked after her
-   tiny dogs
-   she raised Jacqueline O’Connell
-   b 1949 (Laurann’s age, went to school together etc)
-   not allowed outside gateThe doctor in Liverpool said she could have the job if she married him

Mrs Hawksford says “He’ll give you the job if you marry him”

-   she’d be looking out the gate, a lost soul
-   moved to Australia later,
-   Laurann met her briefly in the restaurant but was busy and didn’t give her the time
-   brother Fintan
-   
    -   mother in and out
-   Ground floor was let out to a company

# **Havisham**

Carol Ann Duffy

<https://www.scottishpoetrylibrary.org.uk/poem/havisham/>

Beloved sweetheart bastard. Not a day since then\
I haven’t wished him dead. Prayed for it\
so hard I’ve dark green pebbles for eyes,\
ropes on the back of my hands I could strangle with.

Spinster. I stink and remember. Whole days\
in bed cawing Nooooo at the wall; the dress\
yellowing, trembling if I open the wardrobe;\
the slewed mirror, full-length, her, myself, who did this

to me? Puce curses that are sounds not words.\
Some nights better, the lost body over me,\
my fluent tongue in its mouth in its ear\
then down till I suddenly bite awake. Love’s

hate behind a white veil; a red balloon bursting\
in my face. Bang. I stabbed at a wedding cake.\
Give me a male corpse for a long slow honeymoon.\
Don’t think it’s only the heart that b-b-b-breaks.
