---
title: "Dickens narrated"
---

What the Dickens!

-   where did that fella Dickens come out of?

<!-- -->

-   The Department got him for us. You see our job in the **Old Boro** was to gather up money and free up a premises, then the Department would get you the rest. The machines, the engineers, the managers, the director. **The whole kit and caboodle.** They even came to train the young lads in the town **down** in the new **tech**\[nical college\]. **ADD DETAILS FROM EDDIE - e.g. young Paddy Walsh was top of the class.**

But why was it leather you produced? Dungarvan hadn't had a tannery in generations.

-   Lemass needed soft leathers because Portlaw were doing all the hard leathers and if you're going to be self-sufficient, as he called it, you needed one of everything. No doubling up. We couldn't have set up a hard leather factory because the country already had one. Kennedy O'Brien said it was ideal because we had the river for the work and the sea for the effluent. And we were just down the road.

-   But sure we hadn't a clue. None of us in the town knew anything about leather. I remember Lemass telling us we'd be getting a soft leather factory and one evening I had to go over to ask Rita in the little library if she had any books on leather and how it's made. Of course there was nothing so she sent me up to Lismore to see Frank Murphy in the county library. Frank sent me up to the A.R.C.S. up on Merrion St and they dug out a few trade manuals for us to peruse. Myself and Joe Moloney and Father Tommy were there on the morning of the meeting, frantically reading all these manuals. Then we went over to Bewleys to meet Kennedy O'Brien and he ran through everything we'd need to know for the meeint. **THROW IN A FEW quick DETAILS**

-   Anyway – where was I? Northampton. There was no better place in the world for leather than Northampton \[**explain the land\]**. It's the capital of boot and shoe production. The department sent a couple of civil servants over to assess who'd be the best man for the job. **There was no use getting the bigger leather factories. They had enough going on.** The lads said they loved Dickens's because they had nothing but men working for them. Even the typists in the office were men. There was only about fifty of them and they could see that Reggie was hungry. Give it to the fella that wants the job, they said.

-   

    -   . The *brothers were older than him and he wanted his own show. They were much older a*nd they took over the factory from their father when he had a **coronary**. Like myself. Forty-two or three he was only, I believe. *Then the brothers kept it running during the war while Reggie was off fighting. and when he came back he was further down the line of succession.*

-   Dickens was dyed in the wool leather, leather leather. His father was a leather man and his grandfather too and all his brothers bar the youngest one, Frank. He's much younger. Same age as myself and we always got on like a house on fire. Do you know they're the same as ourselves. Five boys and one girl, but they didn't have to all scatter like ours did.

    -   **We got to know them well over the years / before the war when we went over to visit Northampton**\[???\]

-   But you see Frank is a chemist and a very good one at that. They made him a Fellow of the Royal Society not too long ago, and he has always been able to keep us up to date on the latest developments in the field of chemistry. Reggie gets advice from him, you see, and that keeps us ahead of the game. **I don't know what we'd do without Reggie and Frank.**

    -   Frank barely remembers the father but Reggie told me he was awful strict on them and he never drank. You see the mother was Church of England and not that different from our friends but the father was a Baptist, another breed altogether. He used to give sermons in the village where he grew up. He wasn't even a priest or a pastor or whatever they call themselves. But he was dead against **the evils of** drink. **Richard would have loved him!!!** And they were all great workers. Like the Quakers here in Waterford. They used to set up factories because they weren't allowed into the colleges. Oxford and Cambridge. **But by the time I got to London there were all sorts there**

    -   Anyway so Reggie's father had great experience of setting up a factory himself, and the brothers would have seen a lot of it. He moved into Northampton and set up a workshop in the late '90s but then he built his own factory soon after. He got a big loan from his father-in-law and some from the banks too. Four thousand pounds I believe. That was a lot for one man to take on. They demolished a row of cottages and had the factory built. Right there in the town **beside all the Baptists and the other quare fellas.** He was gone a couple of years later but **Albert and Alfred** took over. Just young fellas not even out of school. Within a few years they were exporting to America and that helped to build the contacts for us. Although that all stopped with the war and they had to supply the British Army of course. After the war they went public so Reggie learnt a lot there. Although he learnt more than his fair share of the war too, driving six horses at a time with all their ammo on the cart, and the Jerries's shells flying at them. Sure we had it easy **in the hills of South Waterford.**

<!-- -->

-   

-   

    -   The lads were all **thick as thieves and played soccer on a Saturday \[rugby in Northampton\].**

-   

    -   because the land is so good round there. **it's not that different to WHERE IN IRELAND. Cows, sheep,fiels**

-   who was a chemist and sure he was a great help too \[**because he taught Reggie and the other brothers everything they needed to know about the newer chemicals and that's why Reggie was so helpful for so long as Technical Director. Sure Frank is in the Royal ???? of Scientists**

-   

<!-- -->

-   He knew everything about Dublin and his father was a professor in UCD. Frank sent me to the library in .
