---
title: "Opening Ceremony"
---

------------------------------------------------------------------------

-   Splendid new leather factory

**Monday, May 3, 1937**

-   Irish Press reports the next day

-   Dungarvan Observer on the Saturday

-   In production for some 12 months

-   Machinery worth £13000

\
Opening:

-   Ireland in 1937 was a land filled with the hope of coming prosperity.

    -   While it was most certainly a repressive theocracy, it was also a state that had begun building towards self-sufficiency through the sudden emergence of an industrial sector thanks in part to the large tariffs that had recently been placed on imported goods.

    -   

The opening of Dickens Leather Factory, on Monday, 3 September, 1937 was a special day in the town's history and it gives us the ideal opportunity to get introduced to the characters in the story and to understand who was who when the factory opened. Officially opened, that is, because the factory was already up and running for fully twelve months (GET DATES) **and, given the circumstances, that was the hard part done, as we shall see.**

The ceremony began with the arrival of Minister Sean Lemass, who was yet again made Minister of Industry and Commerce in the new Dáil of July 1937, where Fianna Fail rubberstamped their authority on the The Irish Free State, winning exactly 50% of seats, before reconstituting the state by the end of the year. Lemass had been most successful in his first ministerial term, opening up countless new factories around the state, including County Waterford's other leather factory in the village of Portlaw.

Lemass alighted in Abbeyside, the village across the bridge from Dungarvan Town, and he we was met by a local priest and most of the directors of Dickens Leather. Fr **T.B.** Walsh was the Chairman of the Dungarvan Industrial Development Association, a group that included two local, Dr Michael Augustine Casey and **Patrick J.** Molony, the managing director of A. Molony and Sons (**shipping?)**This team had agitated hard to get the factory into Dungarvan and the factory in Portlaw proved to be a complementary stepping stone, in terms of both personnel and output. Portlaw's produce was mostly based on hard cowhide leather, used in the soles of the shoes, whereas Dungarvan's produce was mostly based on softer sheepskin leather, used for upper parts of the shoe and inner linings. Their leadership groups were also hugely overlapping. The Chairman of Dickens Leather was Mr Kennedy O'Brien who was becoming something leather baron across Ireland. He was **CHAIR**? of Portlaw, and his core business was as leather merchant in Dublin City. And the Managing Director was the eponymous Reginald Dickens from England, and his family's core business was in Northampton, the most famous city in the world for leather and shoe production. Dungarvan and Portlaw, for him, were side ventures from his main business, run by Reginald and his brothers, and by their father before them since 1897.

The town was ready for its big day and once the men of influence had assembled, the triumphal procession could begin to slither through the freshly decorated streets, to the roars of the crowd, as cheer after cheer rent the air. Varicoloured bunting festooned the main streets and large banners welcomed the Minister to the town. The local Gardaí formed a bodyguard for Lemass and the parade was fronted by the Waterford Brass and Reed band playing familiar airs, many with a nationalistic bent, for the day was an expression of both national and local pride. The crowd filed in behind them like mass-goers forming a queue for communion and, on arrival at Quay Street, they were met by the hundred-plus men who worked in the factory nearby, at The Lookout, looking out at the wide expanse of Dungarvan Bay.

A temporary stand was erected and Lemass was greeted by Kennedy O'Brien in his capacity of Chairman of Dickens Leather. Meanwhile, the band played the National Anthem while the deep crowds looked on. Several welcoming addresses were made. First up were The Urban District Council and then Father Walsh himself. Not one, but two local Fianna Fail groups gave an address: the Padraig Pearse Cumann and the Cathal Brugha Cumannn and, finally, an unidentified of the factory's workforce said some words, with no name given by any of the newspaper reports.

The last public address was made by Lemass himself. He thanked and congratulated the above-mentioned men of power, the workers and his Fianna Fail colleagues in the Cumainn, but also spoke the crowd themselves, noting the importance of the factory in generating employment and prosperity to the locality.

Afterwards, O'Brien presented Lemass with a symbolic gold key to the factory, and, with the church and local government and the politicians having all had their say, and with the band playing Faith of Fathers, it was time for the factory to be blessed solemnly by His Lordship, The Most Reverand Doctor Jeremiah Kinane, Bishop of Waterford and Lismore, ably assisted by the Parish Priest, The Very Reverand T. Canon O'Brien, and his curate, the above-mentioned Reverand TB Walsh.

Afterwards, Dickens gave the Bishop and Minister a guided tour of inspection of the factory

------------------------------------------------------------------------

The factory was left open for the local hoards to investigate and one wonders how well supervised the machines were with children running round.

Later in the day, Lemass would point out how great it was that the factory was a truly local venture – and it certainly was for the staff employed in the factory. But the reality is that the directors were a mix of locals (Austie Casey and Joe Molony) with bigger fish.

In July 1937, Fianna Fail had yet again won the general election, and were continuing their policy of applying huge tariffs on imported goods, a policy which facilitated the growth of an unprecendented number of mid-sized factories around the state. Sean Lemass was again the Minister of Industry and Commerce, a position he would hold between 1932 and 1959 for for sixteen intermittent years.

------------------------------------------------------------------------

The town

-   was en fete for the occasion

-   flags and bunting on all the prinicipal streets

    -   colourful and festive appearance
    -   festooned with bunting and schools beating inscriptions of 'Welcome to the factory'

-   Music

    -   waterford brass and reed band

        -   playhing national and popular airs

-   

-   Arrival Order

    1.  Lemass met at Abbeyside Bridge by
        1.  met by Rev T Walsh, CC, Chairman of Dungarvan Industrial Development Association, and:
            1.  the directors
            2.  members of the urban council
            3.  large gathering of the general public
    2.  A bodyguard of honour of the civic guards
        1.  Chief Superintendant E. Duffy
        2.  Superintendent M. Walsh, Dungarvan
        3.  led by the band: Waterford Brass and Reed Band
    3.  Huge procession marched to the factory
    4.  Factory workers lined up on Quay St (in a guard of honour)
    5.  At the factory
        1.  Minister welcomed by Kennedy O'Brien, chairman of Dickens Leather
        2.  Ascended the platform erected at the esplanade, to the strains of the National Anthem
    6.  Addresses of Welcome
        1.  UDC to the minister, read by the town clerk (Mr William O'Meara), presentee by the Chairman, Mr Ml. Morrissey,
        2.  Rev TB Walsh B.A. C.C.
            1.  Chairman of Dungarvan Industrial Development Association presented an address on behalf of the body
        3.  Padraig Pearse Fianna Fail Cumann
        4.  Cathal Brugha Fianna Fail Cumann
        5.  On behalf of the workers of the factory (Who?)
    7.  Blessing
        1.  Band play Faith of our Fathers
        2.  His Lordship, Most Rev. Dr Kinane, Bishop of Waterford and Lismore, blessed the factory
    8.  Lemass
        1.  Replying to the addresses of welcome
            1.  he wished to thank all the public bodies which had presented him with addresses of welcome, and in a special way, the workers of the factory, and the two Cumainns (FF)
            2.  "If the establisthment of the factory in Dungarvan will help to restoree the prosperity of this town and to provide new opportunities for emplloyment for its young men, any little assistance that I, in my official capacity, might have been able to give will be more than repaid"
            3.  He wished to congratulate the directors of the enterprise on the success which had attended their efforts so far and he hoped that success would be continued in the future
    9.  Opening
        1.  By Minister Lemass with a gold key, presented to him by KOB, after which Most Rev Dr Kinane, Bishop of Waterford & Lismore blessed the factory buildings, assisted by Very Re Canon O'Brien, PP
        2.  Machinery was set in most & Kinane + Mr R Dickens, managing director, made a tour of the factory and evinced great interest in the various processes the hides go through until the finished article is produced ready for despatch.
        3.  Hundreds of the general public also visited the factory during the day
            1.  imagine swathes of sprogs running round and playing with the dangerous machines!!!
            2.  DESCRIBE THE MACHINES
                1.  KOB story
                2.  Portlaw descriptions, what is what & who is who
            3.  
    10. Luncheon
        1.  Egan's Hotel
        2.  Lemass + directors
        3.  Toast of Eire first
        4.  KOB proposed a toast to 'Prosperity of Ireland'
            1.  "A signal honour has been paid to the town of Dungarvan today. The minister has come here to officially open our factory, and his Lordship the Bishop of Waterford has come to impart God's blessing upon our industry. On your behalf and on that of the people of Dungarvan, I wish to thank those distinguished gentlemen"

            2.  "Hear, hear"

            3.  "The establishment in Dungarvan of the important factory is due mainly to the efforts made by the members of the Dungarvan Industrial Devopment Association, working unselfishly in the interests of their native town and of the townspeople. In referreint to the DIDC, I wish to make special reference to the work of the Chairman, Rev Father (T B) Walsh and to the members of the committee, including Dr Michael Casey and PJ Molony. These gentlemen and other members of the committee, to my knowlege, spent many weary months in an effort to secure for the town a suitable industry that would provide much neeede employment. I think everyboyd will agree that their efforts have been successful.

            4.  \[Speaking from a life of experience, he wrote\] The industry is a highly technical one, there is a very large market available within the Irish Free State for its products, \[The first and most difficult period of the company's history has now passed\] and employment is given to over 100 male workers to whom good wages are paid.

            5.  The sales of the company in recent months were higher than even the most optimistic of them had expected when it started and they were still increasing.

            6.  The establishment of the indusry had been brought about as a result of the industrial policy of the government which aimed at making the country self-sufficient, and, ny creating industries for the manufacture of the country's requirements, giving much-needed employment.

                1.  \[include the wage bill here – maybe £300 per week, to be converted to modern money for comparison, but ideally with a list of what that could buy

            7.  I should like to express appreciation to those who invested the necessary capital to permit this industry to be started, said Mr O'Brien. I can assue them that it is now firmly establised, that the company's prospects are, in my opinion, most favourable, and that their interestes will be looked after, to the best of our ability, by me and my co-directors.

            8.  A tribute must be paid to the employees. The managing director has told me that they have adapted themselves very quickly to the training facilities offered to them, and have worked willingly and loyally in the interests of the company.

            9.  The establishment of this industry has been brought about as a result of the industrial policy of the Government, which has as its object the making of this country self-sufficient, and by the creation of industries for the manufacture of the rquirements of the country, giving much-needed employment. From what I have already told you, I think you will agree that this object has been achieved so far as the factory in Dungarvan is concerned.

                1.  IP: @while there might be a feeling of disappointment that a large part of the industrial field was still untilled, very few people were disposed to think that the industrial enterprises set going since the present government took office would ever fall is adequately supported byt heir own opein. And that support, in my opinion, is likely to be forthcoming in ever-increasing measure in the future"

            10. As an example of what has been achieved in the leather industry, said Mr O'Brien, I am asking th Minister to accept a pair of slippers. The upper leather of these slippers has been manufactured from native Irish sheepskin tanned in our factory here in Dungaravan; the sole and insold leather from native cow-hide tanned in the neighbouring factory in Portlaw; the lasts on which they have been manufactured were made in the recently established factory in Newbridge \[lasts are a wooden form on which the leather upper of a shoe is shaped.\], and the manufacture of the slippers themselvers was carried out by the well-known and old-establihsed firm of boot and show manufacturers of Messrs Hearne and Cahill, Waterford. The slippers are presented not for their intrinsic valude as a memento of the work done in the establishment and development of Irish industries by the Minister for Industry and commerce.

            11. Applause

                1.  Find out the yeas in which each of these factories was established

            12. **Just another day at the office for Lemass\
                This is where the cartoon ought to go**

                Replying to the toast, Mr Lemass said thay they had gathered from the newspaper reports that he frequeently had occasion to attend functions like that, and for one holding the position fo Minister for Industry and Commerce it was always a pleasure to be present at such function, but the pleasure was not entirely an unmixed one, because as time passed it became increasingly difficult to say something original. This was the first occasion he was able to visit Dungarvan for a number of years, and he was very glad that the occasion was one associated with the establishment of an industry in the town, \[with characteristic vision, he continued\] a**n industry that would not merely be of considerable benefit to the town at present, but offers considerable prospects of development for the future**, enabling it to extend its roll of its employees, enlarge the sum which is distributed in weekly wages, and thus extending the trade of the town, and help to add to its presperity, and promote the general business activities of the town.

            13. If there is one reason more than another why I am please to be associated with this enterprise, he said, is because in the best and truest sense of the term this is a local enterprise.

                1.  **Of course there was a swathe of outsiders with their fingers in this local pie (Dickens, O'Brien, Crowley)**

            14. 

            15. Mr Lemass continued that the history of the establishment of this factory in Dungarvan would be a source of benefit to the citizens of other towns in the Free State, in which factories of a similar nature had not yet been set up, and where the volume of demand for such a factory had grown in persistence. \[e.g. Carrick-on-Suir for leather, but plenty more other factories\]. He was glad that a tribute had been paid to the local committee because the factory would not have been established at all only for their efforts.

                1.  **whose efforts led to the formation of a company financed without outsdie assistance or the usual underwriting facilities.**

                2.  

            16. At some stage a factory such as this would have been set up in the country, but not necessarily by the compnay which was no operating here, and certainly not in Dungarvan, were it not for the work of the local committee, of which he had personal evidence a long time ago. \[Walsh, Casey, Molony et al\] **They set out to establish an industry here and very quickly established contact with teh Department and he was glad that they were able to assiste them. Again, the company was formed and finance without outside assistance, underwriting facilities or any other financial help, as was due not alone to the promoters but to the good citizenship of the people of Dungaravvan and the locality,**

                1.  it was an investment that showed not only their belief in the industrial future of this countr, but also their confidence in the ability of their own townmen to make good in industrial work.

            17. and he did not think that at any time they would have reaon to regret what they had done and the investment they had made. This industry, like all new industries, had to overcome difficulties, had (?)not been surmounted and the company was progressing very satisfactorily indeed.

            18. **Damn the begrudgers**

                Speaking on the industrial development of the country, the Minister said that what had been said, written and through about the industrial future of this country in past years, was nonsense and was used by those who had vested interests in maintaining the old position. When the opportunity was given for developing the industrial position of the country that opportunity was availed of not by the people of one party or one class, but was availed of by a large numer of people in the country, many of whom differed fundamentally in matters of political policy in other directions.

            19. "In these days of economic stress", said Mr Lemass, "We are all naturally perturbed at the continued existence of unemployment on a wide scale, and emigration, which stopped for a short time, and is now resumed"

                1.  Need to check stats on that. The issue being that there were no jobs abroad now to emigrate to
                2.  No one emigrated to America

            20. He was sure that most thinking people realised that the problem of unemployment and the problem of emigration were both the same, and the social evils to which they gave rise could not be terminated without the greatest degree of industrial development that circumstances would permit.

            21. "Irrespective of the opintions we might hold on a wide variety of things," said Mr Lemass, "there is no substantion section of our people who do not know the urgency of industrial development so that people might be given more employment and a wider variety of employment"

            22. The minister continued by saying that if they could secure the maximum of industrial development, and secure at the same time that needs of the people in housing were adequately catered for, they could usefully occupy the labour of every unemployed man amongst them.

            23. Concluding, the Minister said that they had a number of economoic problems for soluation and a very large number of of social evils to terminate. He trusted that the succes which had met the efforts of the local committed in Dungaravan, which resulted in giving employment to more than one hundred men in the town who would otherwise be idle or forced to emigrate, would encourage other committees in the country to make a special effort to solve their own problems, and he could assure them that if they had any practical plans they could rely on the cooperation of not merely the Dept of INdustry and Commerce, but of every Government department

            24. Applause

            25. Other Toasts\
                Proposing the toast of 'The Company', Rev Fr Walsh, BA, CC, Dungarvan said that the products of the factory had entered most of the homes of this country. \[(t was a matter of nationwide significance. The minister had spoken very highly of them, and it was very kind of him. The local Industrical Development Committe had done as far as it could its best. That day they had seen a body of men at the factory engaged in manufacture, with the knowledge that they were not distributing foreing goods, but engaged in the noble work of making goods for consumption by the Irish people. **The best bulwark the clergy have against Communism, or any other ism"**, said Father Walsh, "the best guarantee of fidelity \[Faith and Fatherland\] we have is the contented working man."

                1.  He concluded by saying that they were deeply indebted to Mr Dickens, who had come there to teach them about the business to which he had given a lifetime.

            26. Supporting the toast, Mr EA Ryan, State Solicitor, said they had taken part in what he considered to be a very momentous event that day. They were there representing as they did **a part of a living generation of Irishmen and women and have taken ....... what has been one of the most extraordinary political and economic revoluations in the history of the world,** and developing towards what he hoped would be **the complete and absolute political and economic freedom of this country.** That might sound extraordinary to some people, but it was a natural expression of thought on his part. Referring to the fishing industry, he said that **the town was once a great fishing town**, and he could remember in his boyhood days seeing fifty or sixty crafts at the quays, and he hoped that in the near future something would again be done for that industry. \[ there are numerous young men who could fin employment int he fishing industry and he hoped that somethign would be done for them\]

            27. MR R Dickens, replying to the toast, said that he had taken on a job of work, and he intended to see it through. He paid tribute to the wonderful cooperation he had received from the people of Dungarvan. \[he was grateful for the consideration which he had receieved from the MinistRY of Industry and Commerce\]

            28. **The toast of "Our Guests" was proposed by Dr M Casey, who, in doing so, said that he wnated to see more people employed in the town, and he wanted to see Dungarvan and the whole of the county prosperous.** \[the opening of the factory was a work for the betterment ofthe people of the country and was a memorable event int he history of the borough of Dungarvan\].

            29. Very Reverand Canon O'Brien, supporting the toast, said that the prosperity of the town was undoubtedly growing. \[the happiest relations existed between the men employed and the management of the factory\] *(a situation that wsa not to last)*

            30. Mrs Redmond, TD, replying to the toast, said that Dungarvan and Waterford as a whole had suffered much in recent years, and, therefore, it was very good to see this industry established. Money and expense had not been thought about in establishing the industry, and she could see no reason why the factory should not have a prosperous future. \[she hoped that the new industry would eb the forerunner of others to come in Dungarvan\] *how many women TDs were there*

            31. Mr PJ LIttle, TD, also replied to the toast, the **proceedings closed with the singing of the National Anthem by all present**.

**Amongst those present at the opening ceremony and luncheon were:**

Speakers in Bold:

Italics means mentioned by the Irish press

How many women?

***Messrs. Kennedy O'Brien,** Chairman, Leather Company\
R. Dickens, Managing Director, do.\
P. J. Moloney, Director, do.\
B. S. Woolnough, Director, do.\
**Dr. M. Casey, Director, do.***

\
*J. T. Freeman, Secretary, do.\
S. Goulding, T.D.\
**P. J. Little, Parliamentary Secretary to the President*****\
***N. Wall, T.D.* <https://en.wikipedia.org/wiki/8th_D%C3%A1il>*\
Mrs. Redmond, T.D. (Tiny Bridget Redmond (nee Mallick)*\
*L. O'Brien \[ private secretary to Lemass\]*\
*M. Morrissey*\
*J. Bowen, B.E.*

\
*S. Moynihan, County Commissioner*\
*Dr. D. T. McCarthy*\
***E. A. Ryan, State Solicitor*****\
***V. Crowley - chairman of Irish Tanners*\
*R. J. Hearne - prominent director\
H. G. Barlow\
J. C. Landy\
J. O'Neill\
J. Lanigan*\
Superintendent M. Walsh, G.S.

\
*Rev. Brother McMahon*\
***Very Rev. T. Canon O'Brien, P.P., Dungarvan*****\
Rev. T. B. Walsh, C.C., B.A., Dungarvan\
***Rev. M. F. Hearne, C.C., do.*\
*Rev. Fr. McGrath, C.C., do.*\
*Very Rev. N. Dunphy, P.P., Abbeyside*\
Rev. M. Power, C.C., do.\
Very Rev. P. Donegan, O.S.A., Dungarvan\
*Rev. T. Power, O.S.A.*

(Minor figures, unmentioned by the Irish Press, but all prominent townspeople)\
Mr. Going\
J. Christopher, Junr.\
M. O'Meara\
J. Mansfield\
T. C. Williams, solr.\
A. R. Farrell, solr.\
L. Lanigan, solr.\
J. H. O'Sullivan\
T. B. Boyle\
W. O'Meara\
J. McGrath\
An Fear Mor\
B. Mulcahy\
M. Casey\
J. Christopher (Senr.)\
P. I. Stokes\
P. A. Casey\
A. M. Donald\
S. O'Brien\
Dr. O'Keeffe\
Chief Superintendent E. O'Duffy\
J. Cartwright\
Dr. M. Farrell\
R. Moloney\
L. Meehan

\*\*\*

Different reports on the day

-   Dungarvan Observer, blow by blow, step by step account on the Saturday

-   Irish Press - similar but marginally less detailed. For example, local figures present at the special luncheon – including P.A. Casey - are not listed. But politicians, directors, clergy etc all are.

-   Cork Examiner

    -   explains a lot about the factory - machinery, location, stocks etc

Portlaw Opening

-   included Dickens, Austie Casey &
