### **The changing state of the leather industry in Ireland.**

Plots

-   map of tanneries & footwear factories in Ireland

-   bubbleplot showing the number of employees in each factory over time (GET THE DATA)

**Timeline for chapter**

-   1820-1930: Decline

-   1930s Resurrection (THIS OVERLAPS WITH KENNEDY O'BRIEN PROFILE)

    -   Location (ALSO OVERLAPS WITH KOB)

-   1940s variation? (MISSING)

-   1950s Peak and slow decline (MISSING)

**1830s Peak**

The emergence of a leather industry in 1930s Ireland was akin to a resurrection from a long and painful death. The previous hundred years had seen a steady decline of a once-flourishing native industry. The peak was in the 1820s and '30s around the time that livestock began to be exported en masse to Britain, thanks to improvements in sea communications, and thus there fewer and fewer hides available for tanning. In 1837 there were 46 tanneries in the city of Cork alone, tanning over 2000 hides per week. and employing 625 people, which is more people than were employed across the twenty-six counties at the height of the resurrection in the 1950s. T**o grasp the proliferation of the industry in comparison, it may be instructive to compare it to sports clubs in the modern day. Currently, there are 225 GAA clubs in the county of Cork alone, and over 1600 hundred on the island, whereas there are just 109 rugby clubs on the island, many of them clustered in a few hubs. And just as almost every parish nowadays has its own GAA club, every town and village in pre-famine Ireland would have had a tanyard, alongside at least one person making shoes and another repairing them.**

**Decline**

By 1852, after The Great Hunger had destroyed the nation, there were still 26 tanneries in Cork City, although few of them were operating full-time as demand for leather had understandably dropped and credit was scarce so the businesses couldn't get back on their feet. By 1902, there were just three tanneries in Cork and just 18 across the entire island of Ireland. In 1923, **when a Free State report was commissioned,** there were just five. The only large-scale operation was Callaghans in Limerick City, tanning 200 hides per week, and small operation in Thomastown, Clonmel, Ballitore and New Ross, tanning just 100 hiders per week between them. In total, these tanneries were supplying on one twentieth of the state's demand for leather, so the other 95% had to be imported. Even so, New Ross would close down the following year.

The reasons for the decline of the leather industry thus provide us with something of a microcosm of the problems that Ireland faced during the tragic century between the 1820s and 1920s. A tannery needs two things more than anything else: animal skins and dyes for tanning, and both of these were being purged from the country. Livestock were shipped to Britain in ever-increasing numbers and with them vanished the jobs associated with processing the animals, such as butchering the flesh and tanning the skins. Meanwhile, dyes taken from oak bark were becoming harder to source due to deforestation, although by our time of interest, different dyes were being used. A completely different, and preventable problem, was in how duties were levied on tanners. In England, tanners paid duty on every hide processed whereas in Ireland they paid duty on the pits used for processing them, so too many hides would be processed in the one pit, resulting in lower quality leather being made throughout Ireland, and thus greater demand for leather imported from across the pond. Finally, there was little hope of any Irish tanneries exporting leather to Britain, seeing as Britain imposed a 60% tariff on Irish leather but there was only a 10% tariff in the opposite direction.

**Shoots of growth**

Between 1922 and 1932, there was no improvement in the leather industry, although there was a little growth in the footwear industry and these helped paved the way for native leather production which could then be used as a raw material for footwear. In 1924, small tariffs of 15% were introduced on footwear sales in Ireland, but British manufacturers were mostly efficient enough to outprice the emerging batch of Irish producers. However, UK-based businesses began to arrive in The Free State with Edward Donaghy bringing his entire business over the border to Dundalk and, in 1928, John Halliday of Leeds also set up a factory in Dundalk. Later, County Louth would become something of a hub for the Irish footwear industry. The same year, the Irish Tanners Foundation decided that they also wanted some support, so they lodged a case with the newly-formed Tariff Commission, but all they got was a little support in putting tariffs

This of course changed with the arrival the Fianna Fail government in 1932

Location

While the emerging footwear industry was clustered along the
